const GLOSSARY = [
  { key: "austrias", pattern: "\\b(?:Austrias|Habsburgo|Habsburgos)\\b", title: "Los Austrias", definition: "La dinastía de los Habsburgo que gobernó la monarquía hispánica entre los siglos XVI y XVIII. En Madrid dejó el trazado y muchos edificios del entorno de Plaza Mayor." },
  { key: "real-sitio", pattern: "\\bReal sitio\\b", title: "Real sitio", definition: "Lugar vinculado a la Corona, normalmente con palacio, jardines y edificios de servicio." },
  { key: "cornisa", pattern: "\\bcornisa\\b", title: "Cornisa", definition: "Borde elevado de una meseta o terraza. La cornisa de la Almudena asoma sobre el Campo del Moro y la Casa de Campo." },
  { key: "almudena", pattern: "\\bAlmudena\\b", title: "Almudena", definition: "Nombre de la patrona de Madrid. La catedral está dedicada a Santa María la Real de la Almudena." },
  { key: "almadraba", pattern: "\\balmadraba\\b", title: "Almadraba", definition: "Arte tradicional de pesca del atún rojo mediante redes fijas en la costa. El término aparece en las cartas del mercado." },
  { key: "gourmet", pattern: "\\bGourmet Experience\\b", title: "Gourmet Experience", definition: "Espacio gastronómico de El Corte Inglés con puestos de comida y una terraza panorámica sobre Callao y Gran Vía." },
  { key: "zbedep", pattern: "\\bZBEDEP\\b", title: "ZBEDEP", definition: "Zona de Bajas Emisiones de Especial Protección. El vehículo ECO puede acceder, pero conviene comprobar siempre las reglas y el parking elegido." },
  { key: "colegiata", pattern: "\\bcolegiata\\b", title: "Colegiata", definition: "Iglesia atendida por un colegio de canónigos, sin ser necesariamente sede de un obispo." }
].map((entry) => ({ ...entry, matcher: new RegExp(`^(?:${entry.pattern})$`, "iu") }));
const GLOSSARY_PATTERN = new RegExp(GLOSSARY.map((entry) => entry.pattern).sort((a, b) => b.length - a.length).join("|"), "giu");
function glossaryMarkup(value = "") {
  return String(value).replace(GLOSSARY_PATTERN, (match) => { const entry = GLOSSARY.find((item) => item.matcher.test(match)); return entry ? `<button class="glossary-term" type="button" data-glossary="${entry.key}" aria-haspopup="dialog">${match}</button>` : match; });
}

const STOPS = [
  { id: 1, slug: "plaza-mayor", name: "Plaza Mayor", shortName: "Plaza Mayor", subtitle: "Inicio · parking y Madrid de los Austrias", coordinates: { lat: 40.4154, lng: -3.7074 }, duration: "15–20 min", price: "Exterior gratuito", description: "Deja el coche en el aparcamiento de Plaza Mayor y empieza mirando la plaza como una escena cerrada: la Casa de la Panadería, los soportales, la estatua ecuestre de Felipe III y el Arco de Cuchilleros. Es el mejor punto para situar el antiguo corazón comercial de Madrid.", curiosity: "La plaza ha cambiado de nombre y de aspecto varias veces, y ha sobrevivido a incendios, corridas y celebraciones públicas.", timeline: [{ date: "1617", label: "Plaza Mayor", text: "Juan Gómez de Mora ordena el gran espacio porticado sobre la antigua plaza del Arrabal." }, { date: "1848", label: "Felipe III", text: "La estatua ecuestre vuelve al centro de la plaza, donde permanece hoy." }], details: [{ kind: "look", label: "Fíjate en esto", title: "El Arco de Cuchilleros", text: "Baja por el arco del lado suroeste. Su gran escalera salva el desnivel entre la plaza y Cava de San Miguel.", extra: "Ese pequeño cambio de cota explica por qué el siguiente tramo se siente como una salida de la plaza hacia un barrio más antiguo." }], source: "https://www.esmadrid.com/informacion-turistica/plaza-mayor-madrid", image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Plaza_Mayor_de_Madrid_-_01.jpg", alt: "Plaza Mayor de Madrid con sus soportales y la Casa de la Panadería", imageWidth: 1600, imageHeight: 1067 },
  { id: 2, slug: "meson-del-champinon", name: "Mesón del Champiñón", shortName: "El Champiñón", subtitle: "Cava de San Miguel · aperitivo", coordinates: { lat: 40.4144, lng: -3.7081 }, duration: "20–30 min", price: "Consumición", description: "Baja desde el Arco de Cuchilleros y detente en Cava de San Miguel, 17. El Mesón del Champiñón funciona mejor como aperitivo breve: una ración para compartir y algo de beber antes de entrar al mercado.", curiosity: "Sus champiñones al ajillo se sirven en una sala abovedada que conserva el ambiente de las antiguas cuevas y bodegas de esta ladera.", timeline: [{ date: "Siglo XVII", label: "Cavas y bodegas", text: "El desnivel bajo la plaza favorece locales subterráneos, almacenes y tabernas." }, { date: "Hoy", label: "Parada breve", text: "El local conserva el ritual castizo de la tapa rápida antes de seguir caminando." }], details: [{ kind: "context", label: "Cómo usar esta parada", title: "No la conviertas en la comida", text: "Pide una ración de champiñones y una bebida. El Mercado de San Miguel está a pocos minutos y ofrece mucha más variedad para comer.", extra: "Si hay cola, continúa hacia el mercado: el recorrido no depende de sentarte aquí." }], source: "https://mesondelchampinon.com/", image: "https://upload.wikimedia.org/wikipedia/commons/d/df/Calle_Cava_de_San_Miguel_-_03.jpg", alt: "Cava de San Miguel junto a la Plaza Mayor de Madrid", imageWidth: 1600, imageHeight: 1067 },
  { id: 3, slug: "mercado-de-san-miguel", name: "Mercado de San Miguel", shortName: "San Miguel", subtitle: "Comida compartida · hierro y cristal", coordinates: { lat: 40.4154, lng: -3.7091 }, duration: "45–60 min", price: "25–40 € por persona", description: "El mercado queda al final de Cava de San Miguel. Recorre primero todos los puestos y después decide: bacalao o fritura, croquetas, atún rojo de almadraba, jamón, quesos y un postre para compartir. Llegar antes de las 13:30 suele facilitar encontrar sitio.", curiosity: "La estructura de hierro y cristal se inauguró en 1916 como mercado de abastos; su segunda vida gastronómica comenzó en 2009.", timeline: [{ date: "1916", label: "Mercado de abastos", text: "Se inaugura la estructura metálica diseñada por Alfonso Dubé y Díez." }, { date: "2009", label: "Mercado gastronómico", text: "El edificio reabre con puestos de producto y cocina preparada." }], details: [{ kind: "look", label: "Pedido recomendado", title: "Comparte, no acumules", text: "Para dos: bacalao, croquetas, una tapa de atún o fritura, una pequeña tabla de ibéricos o quesos y dos vermuts.", extra: "La Casa del Bacalao, El Señor Martín, Arzábal Croquetería, Tatún, MAS Gourmets, Quesoba y La Hora del Vermut son buenos puntos de partida; la oferta puede cambiar.", prompt: "Después del mercado, la terraza de Callao será solo para café, postre o una copa." }], source: "https://mercadodesanmiguel.es/", sourceExtra: "https://mercadodesanmiguel.es/puestos/", sourceExtraLabel: "Puestos y restaurantes", image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Mercado_de_San_Miguel_-_Madrid_01.jpg", alt: "Interior del Mercado de San Miguel de Madrid", imageWidth: 1600, imageHeight: 1067 },
  { id: 4, slug: "plaza-de-la-villa", name: "Plaza de la Villa", shortName: "Plaza de la Villa", subtitle: "Madrid de los Austrias · un desvío que sí compensa", coordinates: { lat: 40.4153, lng: -3.7103 }, duration: "20–25 min", price: "Exterior gratuito", description: "Desde San Miguel, toma Conde de Miranda, la plaza del Conde de Barajas y la calle del Codo antes de llegar a Plaza de la Villa. El desvío es corto y conserva una escala medieval que se pierde si se camina solo por Calle Mayor.", curiosity: "La Casa y Torre de los Lujanes, la Casa de Cisneros y la antigua Casa de la Villa reúnen en pocos metros varios siglos de arquitectura civil.", timeline: [{ date: "Edad Media", label: "Plaza de San Salvador", text: "El espacio se forma junto a la iglesia y al antiguo centro de gobierno de la villa." }, { date: "Siglos XV–XVI", label: "Casas de linaje", text: "Se levantan las torres y palacios que todavía definen la plaza." }], details: [{ kind: "look", label: "Fíjate en esto", title: "La calle del Codo", text: "Es una de las calles más estrechas y reconocibles del barrio. Mira cómo la curva protege la intimidad de las fachadas.", extra: "Al salir hacia Calle Mayor, busca los restos de la antigua iglesia de Santa María en la esquina de la Almudena." }], source: "https://www.esmadrid.com/informacion-turistica/plaza-villa", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20la%20Villa%20Madrid.jpg", alt: "Plaza de la Villa con la Casa de los Lujanes en Madrid", imageWidth: 1600, imageHeight: 1067 },
  { id: 5, slug: "almudena-y-cornisa", name: "Almudena y mirador de la Cornisa", shortName: "Almudena", subtitle: "Catedral · Plaza de la Armería · vistas al oeste", coordinates: { lat: 40.4156, lng: -3.7147 }, duration: "25–35 min", price: "Exterior gratuito", description: "Continúa por Calle Mayor hasta la Catedral de la Almudena. Rodéala por la Plaza de la Armería y detente en la cornisa: desde aquí se entiende la relación entre el Palacio Real, el Campo del Moro y la Casa de Campo.", curiosity: "La catedral se consagró en 1993, aunque su construcción comenzó en 1883 y atravesó cambios de proyecto y décadas de interrupciones.", timeline: [{ date: "1883", label: "Primera piedra", text: "Comienza el proyecto de una gran catedral para la capital." }, { date: "1993", label: "Consagración", text: "Juan Pablo II consagra el templo, ya convertido en catedral de Madrid." }], details: [{ kind: "look", label: "Fíjate en esto", title: "Dos fachadas, dos lenguajes", text: "La fachada principal mira al Palacio y adopta una composición clasicista; la cabecera y la cripta muestran un lenguaje neogótico más marcado.", extra: "La visita interior de la catedral y la cúpula puede añadir tiempo: aquí basta con rodear el exterior y disfrutar de la cornisa." }], source: "https://www.catedraldelaalmudena.es/", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Catedral%20de%20la%20Almudena%20Madrid.jpg", alt: "Fachada de la Catedral de la Almudena junto al Palacio Real", imageWidth: 1600, imageHeight: 1067 },
  { id: 6, slug: "palacio-real", name: "Palacio Real", shortName: "Palacio Real", subtitle: "Plaza de la Armería · exterior o visita interior", coordinates: { lat: 40.4179, lng: -3.7143 }, duration: "25–35 min exterior · 90 min interior", price: "Exterior gratuito · entrada interior", description: "Cruza la Plaza de la Armería hacia el Palacio Real. Para una visita exterior, quédate con la fachada, la plaza y la conexión visual con la Almudena. Si entras, reserva al menos 90 minutos entre controles, salas y salida; comprueba antes horarios y posibles actos oficiales.", curiosity: "El palacio actual ocupa el lugar del antiguo Alcázar, destruido por un incendio en la Nochebuena de 1734.", timeline: [{ date: "1734", label: "Incendio del Alcázar", text: "El antiguo palacio de los Austrias queda destruido por un incendio." }, { date: "1738–1755", label: "Palacio nuevo", text: "Felipe V encarga el edificio actual, terminado bajo Fernando VI." }], details: [{ kind: "look", label: "Fíjate en esto", title: "La plaza como escenario", text: "Colócate en el eje de la Puerta del Príncipe y mira cómo la fachada se convierte en telón de fondo de la plaza.", extra: "La Galería de las Colecciones Reales queda junto a la plaza: añádela solo si quieres sacrificar tiempo de paseo por una visita interior adicional." }], source: "https://www.patrimonionacional.es/visita/palacio-real-de-madrid", sourceExtra: "https://tickets.patrimonionacional.es/es/tickets/palacio-real-de-madrid", sourceExtraLabel: "Entradas y horarios", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Palacio%20Real%20de%20Madrid%20Spain.jpg", alt: "Fachada principal del Palacio Real de Madrid", imageWidth: 1600, imageHeight: 1067 },
  { id: 7, slug: "plaza-de-oriente", name: "Plaza de Oriente y Teatro Real", shortName: "Plaza de Oriente", subtitle: "Real sitio · transición hacia Ópera", coordinates: { lat: 40.4188, lng: -3.7118 }, duration: "15–20 min", price: "Gratuita", description: "Sal del Palacio hacia la Plaza de Oriente. El Teatro Real, la fila de esculturas de reyes y los jardines forman el último gran espacio monumental antes de que el paseo se vuelva más urbano y comercial.", curiosity: "Las esculturas de reyes fueron diseñadas para coronar el Palacio Real, pero su peso hizo que se repartieran por distintos lugares de Madrid.", timeline: [{ date: "1817–1850", label: "Teatro Real", text: "Se construye y abre el gran teatro situado frente al palacio." }, { date: "1844", label: "Jardines y esculturas", text: "La plaza se ordena como espacio representativo del Real sitio." }], details: [{ kind: "look", label: "Fíjate en esto", title: "La curva del teatro", text: "Rodea unos metros el Teatro Real y mira cómo su volumen circular organiza la plaza y dirige la vista hacia el palacio.", extra: "Continúa por Isabel II hacia Ópera; desde aquí empieza un tramo continuo, sin necesidad de volver atrás." }], source: "https://www.esmadrid.com/informacion-turistica/plaza-oriente", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20Oriente%20Madrid.jpg", alt: "Plaza de Oriente y Teatro Real de Madrid", imageWidth: 1600, imageHeight: 1067 },
  { id: 8, slug: "opera-y-sol", name: "Ópera, Arenal y Puerta del Sol", shortName: "Sol", subtitle: "Del teatro a la plaza más transitada", coordinates: { lat: 40.4169, lng: -3.7035 }, duration: "25–35 min", price: "Gratuita", description: "Baja por la calle Arenal y entra en la Puerta del Sol. En el trayecto busca la iglesia de San Ginés; ya en la plaza, localiza la Real Casa de Correos, el Kilómetro Cero, el Oso y el Madroño, el cartel de Tío Pepe y Carlos III.", curiosity: "El Kilómetro Cero no está exactamente en el centro geométrico de España: marca el origen convencional de las carreteras radiales frente a la Casa de Correos.", timeline: [{ date: "1858", label: "Puerta del Sol", text: "La gran reforma de la plaza consolida su forma abierta y su papel de nodo urbano." }, { date: "1919", label: "Metro de Madrid", text: "La primera línea del metro conecta Sol con Cuatro Caminos." }], details: [{ kind: "context", label: "Ritmo del paseo", title: "Cruza, no te quedes atrapado", text: "Sol es un lugar de paso. Haz una vuelta corta por el perímetro y sube por Preciados hacia Callao.", extra: "La ruta reserva la pausa con vistas para la siguiente parada." }], source: "https://www.esmadrid.com/informacion-turistica/puerta-sol", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Puerta%20del%20Sol%20Madrid.jpg", alt: "Puerta del Sol de Madrid con la Casa de Correos", imageWidth: 1600, imageHeight: 1067 },
  { id: 9, slug: "callao-gourmet-experience", name: "Callao y terraza de El Corte Inglés", shortName: "Callao", subtitle: "Gourmet Experience · panorámica de Gran Vía", coordinates: { lat: 40.4202, lng: -3.7058 }, duration: "30–45 min", price: "Consumición", description: "Sube por Preciados hasta Callao y entra en El Corte Inglés de Plaza de Callao, 2. La Gourmet Experience de la planta 9 es la pausa ideal para café, postre, una cerveza o una copa: no hace falta volver a comer después del mercado.", curiosity: "Desde la terraza se ve el edificio Capitol y la curva de Gran Vía como una escenografía urbana continua.", timeline: [{ date: "1929", label: "Edificio Carrión", text: "Se inaugura el edificio Capitol, convertido en uno de los iconos de Callao." }, { date: "Hoy", label: "Terraza panorámica", text: "El espacio gastronómico ofrece una de las vistas más fáciles de disfrutar del centro." }], details: [{ kind: "look", label: "Fíjate en esto", title: "Gran Vía en profundidad", text: "Desde la terraza, alinea el Capitol, los teatros y el Edificio España. Es una lectura rápida de cómo la avenida cose el centro moderno.", extra: "El acceso y los horarios pueden variar; si la terraza está cerrada, continúa directamente por Gran Vía." }], source: "https://www.elcorteingles.es/centroscomerciales/es/eci/centros/centro-comercial-preciados-callao", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Plaza%20de%20Callao%20Madrid.jpg", alt: "Plaza de Callao y el edificio Capitol de Madrid", imageWidth: 1600, imageHeight: 1067 },
  { id: 10, slug: "gran-via-plaza-espana", name: "Gran Vía y Plaza de España", shortName: "Gran Vía", subtitle: "La avenida espectáculo · transición al parque", coordinates: { lat: 40.4231, lng: -3.7118 }, duration: "25–35 min", price: "Gratuita", description: "Camina hacia el oeste por Gran Vía sin intentar verlo todo. Quédate con el Capitol, los teatros, el Edificio España y la Torre de Madrid. En Plaza de España, detente ante Cervantes, Don Quijote y Sancho antes de subir hacia Debod.", curiosity: "La Gran Vía se abrió por fases desde 1910 y cortó el tejido de calles estrechas para crear una avenida comercial y de espectáculos.", timeline: [{ date: "1910", label: "Primera obra", text: "Alfonso XIII coloca la primera piedra del gran eje que transformará el centro." }, { date: "1929", label: "Tramo de Callao", text: "Se completa el tramo central, con cines, hoteles y grandes almacenes." }], details: [{ kind: "look", label: "Fíjate en esto", title: "La ciudad como fachada", text: "Mira arriba: cada tramo de Gran Vía cambia de escala, desde las marquesinas de los teatros hasta los rascacielos de Plaza de España.", extra: "Al llegar a la plaza, cruza por el paseo central y toma el camino peatonal hacia Debod." }], source: "https://www.esmadrid.com/informacion-turistica/gran-via", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Gran%20Via%20Madrid%20Spain.jpg", alt: "Gran Vía de Madrid con sus edificios y carteles luminosos", imageWidth: 1600, imageHeight: 1067 },
  { id: 11, slug: "templo-de-debod", name: "Templo de Debod", shortName: "Templo de Debod", subtitle: "Final · puesta de sol y regreso circular", coordinates: { lat: 40.4240, lng: -3.7177 }, duration: "30–45 min", price: "Exterior gratuito", description: "Llega entre 30 y 45 minutos antes de la puesta de sol. Rodea el templo, mira hacia el oeste y deja que el parque haga de pausa final. El templo egipcio fue trasladado piedra a piedra a Madrid en 1968 como agradecimiento por la ayuda española en Nubia.", curiosity: "Es uno de los pocos templos egipcios completos que pueden verse fuera de Egipto, y su reflejo en el estanque depende mucho de la temporada y del nivel de agua.", timeline: [{ date: "Siglo II a. C.", label: "Templo egipcio", text: "El rey Adijalamani levanta el núcleo del templo dedicado a Amón e Isis." }, { date: "1968", label: "Llegada a Madrid", text: "España recibe el templo tras colaborar en el salvamento de monumentos de Nubia." }], details: [{ kind: "look", label: "Regreso al parking", title: "Vuelve por una línea distinta", text: "Desde Debod: Plaza de España → Leganitos → Santo Domingo → Campomanes → Arrieta → Ópera → Vergara → Ramales → Santiago → Milaneses → Calle Mayor → Plaza Mayor.", extra: "Son aproximadamente 30–35 minutos. Solo repites el corto tramo entre Debod y Plaza de España; no vuelves por Gran Vía, Arenal ni Plaza de Oriente.", prompt: "Acción final: abre la navegación peatonal hacia el parking de Plaza Mayor." }], source: "https://www.esmadrid.com/informacion-turistica/templo-debod", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Templo%20de%20Debod%20Madrid.jpg", alt: "Templo de Debod al atardecer en Madrid", imageWidth: 1600, imageHeight: 1067, return: true }
];
const GALLERY = { id: 12, slug: "galeria-colecciones-reales", name: "Galería de las Colecciones Reales", shortName: "Galería Real", subtitle: "Parada opcional · junto al Palacio Real", coordinates: { lat: 40.4174, lng: -3.7136 }, duration: "60–90 min", price: "Entrada", description: "Añade esta visita interior después del Palacio Real solo si quieres ampliar el recorrido hacia las colecciones de la Corona. Comprueba entradas y horarios: la Galería cambia por completo el ritmo del día.", curiosity: "Su recorrido conecta piezas de distintas residencias reales con una arquitectura excavada junto a la cornisa del Palacio.", timeline: [{ date: "2018", label: "Inicio de obras", text: "El proyecto museístico se prepara junto a la Plaza de la Armería." }, { date: "2023", label: "Apertura", text: "La Galería abre al público con piezas de los Reales Sitios." }], source: "https://www.galeriadelascoleccionesreales.es/", sourceExtra: "https://tickets.patrimonionacional.es/", sourceExtraLabel: "Entradas y horarios", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Galeria%20de%20las%20Colecciones%20Reales%20Madrid.jpg", alt: "Interior de la Galería de las Colecciones Reales", imageWidth: 1600, imageHeight: 1067, optional: true };
const IMAGE_URLS = {
  1: "https://upload.wikimedia.org/wikipedia/commons/5/58/Plaza_Mayor_de_Madrid_-_01.jpg",
  2: "https://upload.wikimedia.org/wikipedia/commons/d/df/Calle_Cava_de_San_Miguel_-_03.jpg",
  3: "https://upload.wikimedia.org/wikipedia/commons/7/70/Mercado_de_San_Miguel_-_Madrid_01.jpg",
  4: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Plaza_de_la_Villa_-_08.jpg",
  5: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Catedral_de_la_Almudena_-_130826_211731.jpg",
  6: "https://upload.wikimedia.org/wikipedia/commons/8/89/Madrid_-_Palacio_Real_01.jpg",
  7: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Madrid_Plaza_Oriente_R02.jpg",
  8: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Interior_%C3%81rbol_de_Navidad_--_2013_--_Puerta_del_Sol%2C_Madrid%2C_Espa%C3%B1a.jpg",
  9: "https://upload.wikimedia.org/wikipedia/commons/4/48/Raining_Day_at_plaza_del_Callao%2C_Madrid.jpg",
  10: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Madrid_-_Edificio_Grassy_%28Gran_V%C3%ADa_1%29_-_north_facade_-_relief_over_entrance.jpg",
  11: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Templo_de_Debod_-_01.jpg",
  12: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Galeria_de_las_Colecciones_Reales_-_Madrid_02.jpg"
};
const ROUTE_ORDER = [1, 3, 4, 5, 6, 7, 11, 10, 9, 8, 2];
const mesonStop = STOPS.find((stop) => stop.id === 2);
if (mesonStop) {
  mesonStop.subtitle = "Cierre gastronómico · junto al parking";
  mesonStop.description = "Después de volver desde Debod por Santo Domingo, Ópera y Calle Mayor, baja unos pasos desde Plaza Mayor hasta Cava de San Miguel, 17. El Mesón del Champiñón es el cierre perfecto: una cerveza y una ración para compartir antes de recoger el coche.";
  mesonStop.details = [{ kind: "context", label: "Cómo cerrar la ruta", title: "Una última cerveza, sin rodeo", text: "Reserva 20–30 minutos para los champiñones y la bebida. Desde aquí el parking de Plaza Mayor queda a pocos minutos a pie.", extra: "El horario puede variar y el local suele llenarse; si conduces después, elige cerveza 0,0 o deja que conduzca otra persona." }];
}
const debodStop = STOPS.find((stop) => stop.id === 11);
if (debodStop) {
  debodStop.subtitle = "Parada intermedia · Parque del Oeste";
  debodStop.description = "Llega al Templo de Debod desde el entorno del Palacio por Bailén, la Cuesta de San Vicente y el Paseo de Rosales. El templo y el parque funcionan aquí como una pausa abierta antes de volver a entrar en la ciudad por Plaza de España.";
  debodStop.details = [{ kind: "look", label: "Cómo continuar", title: "Sal hacia Plaza de España", text: "Rodea el templo y cruza el Parque del Oeste hacia Ferraz y Plaza de España. No hace falta esperar al atardecer: esta parada funciona igual de bien como mirador y descanso durante el día.", extra: "Desde Plaza de España continúa hacia el este por Gran Vía, Callao, Preciados y Sol. El circuito termina cerca del parking, no en Debod." }];
}
const operaStop = STOPS.find((stop) => stop.id === 7);
if (operaStop) {
  operaStop.name = "Plaza de Oriente, Teatro Real y Ópera";
  operaStop.shortName = "Oriente / Ópera";
  operaStop.subtitle = "Real sitio · conexión hacia Debod";
  operaStop.description = "Sal del Palacio hacia la Plaza de Oriente y el Teatro Real. Después pasa por Ópera y toma Bailén hacia la Cuesta de San Vicente y el Paseo de Rosales: así el recorrido avanza hacia Debod sin bajar por Arenal ni volver después sobre sus pasos.";
  operaStop.details = [{ kind: "look", label: "Fíjate en esto", title: "Tres plazas, una transición", text: "Plaza de Oriente, Ópera y Bailén cambian la escala del paseo: del espacio ceremonial del Palacio a la salida hacia el parque y Debod.", extra: "La calle Arenal y Puerta del Sol quedan para el tramo posterior, después de Gran Vía y Callao." }];
}
const solStop = STOPS.find((stop) => stop.id === 8);
if (solStop) {
  solStop.name = "Puerta del Sol";
  solStop.shortName = "Sol";
  solStop.subtitle = "Último tramo urbano · regreso al centro";
  solStop.description = "Desde Callao baja por Preciados hasta la Puerta del Sol. Haz una vuelta breve por la Real Casa de Correos, el Kilómetro Cero, el Oso y el Madroño, el cartel de Tío Pepe y Carlos III antes de continuar por Calle Mayor hacia Plaza Mayor.";
  solStop.details = [{ kind: "context", label: "Ritmo del cierre", title: "Ya estás cerca del coche", text: "Sol es la última gran plaza del paseo. Desde aquí son aproximadamente 10–12 minutos hasta el Mesón del Champiñón y pocos minutos más hasta el parking.", extra: "Si vas justo de tiempo, Sol puede hacerse en una vuelta rápida sin añadir otro desvío." }];
}
const granViaStop = STOPS.find((stop) => stop.id === 10);
if (granViaStop) {
  granViaStop.subtitle = "Plaza de España → Gran Vía · dirección este";
  granViaStop.description = "Desde Plaza de España entra en Gran Vía y camina hacia el este. Quédate con el Edificio España, la Torre de Madrid, los teatros y la secuencia de fachadas que conduce hasta Callao.";
  granViaStop.details = [{ kind: "look", label: "Fíjate en esto", title: "Una avenida en dirección al centro", text: "El tramo se entiende mejor caminando hacia Callao: los edificios cambian de escala y la ciudad se vuelve cada vez más comercial.", extra: "Al llegar a Callao, entra en El Corte Inglés si la Gourmet Experience está abierta; después continúa por Preciados hasta Sol." }];
}
const callaoStop = STOPS.find((stop) => stop.id === 9);
if (callaoStop) {
  callaoStop.description = "Tras recorrer Gran Vía hacia el este, detente en Callao y entra en El Corte Inglés de Plaza de Callao, 2. La Gourmet Experience de la planta 9 es la pausa ideal para café, postre, una cerveza o una copa: no hace falta volver a comer después del mercado.";
}

// La ruta se lee como una historia urbana continua: de villa medieval a capital,
// de ciudad cortesana a metrópolis moderna y, finalmente, a una ciudad global.
const HISTORICAL_COPY = {
  1: {
    subtitle: "Acto I · la villa que se convierte en capital",
    description: "Antes de ser una plaza monumental, este era el Arrabal: el mercado que crecía fuera de las murallas medievales. Cuando Felipe II fijó la corte en Madrid en 1561, aquel borde comercial quedó en el centro de una capital nueva. Juan Gómez de Mora lo ordenó desde 1617 y la plaza se inauguró en 1620. Mira los soportales como un escenario: aquí se vendía, se celebraba, se juzgaba y se representaba el poder.",
    curiosity: "La Plaza Mayor fue plaza de toros y escenario de fiestas, juegos de cañas, autos de fe y ejecuciones públicas. No eran el mismo ritual: el auto de fe era una ceremonia religiosa y la ejecución, un castigo penal. Tres grandes incendios (1631, 1672 y 1790) obligaron a rehacerla varias veces.",
    timeline: [
      { date: "1561", label: "La corte llega a Madrid", text: "Felipe II fija aquí la capital y el antiguo arrabal empieza a transformarse en centro político." },
      { date: "1620", label: "Plaza Mayor", text: "Se inaugura la gran plaza porticada bajo el reinado de Felipe III." },
      { date: "1790", label: "Tercer incendio", text: "La reforma de Juan de Villanueva da a la plaza buena parte de su aspecto actual." }
    ],
    details: [{ kind: "look", label: "Lee la plaza", title: "Un teatro de la vida pública", text: "Sitúate frente a la Casa de la Panadería y observa las fachadas como gradas. La plaza estaba diseñada para que la multitud mirara hacia el centro y hacia los balcones.", extra: "Después baja por el Arco de Cuchilleros: saldrás del espacio oficial hacia la ladera de tabernas, almacenes y antiguas cavas." }]
  },
  2: {
    subtitle: "Epílogo castizo · una ciudad que sigue comiendo",
    description: "El Mesón del Champiñón es la última escena del paseo, cuando ya has visto cómo Madrid se hizo capital y metrópolis. Baja al número 17 de Cava de San Miguel y entra en una de esas bodegas que aprovechan el desnivel bajo la Plaza Mayor. Pide una cerveza y una ración para compartir: aquí la historia no está en un monumento, sino en la continuidad de la taberna como forma de vida urbana.",
    curiosity: "El local abrió en 1964 y conserva la atmósfera abovedada de las cavas bajo la plaza. El champiñón al ajillo es sencillo, pero el ritual —barra, tapa y conversación— conecta con la cultura popular del centro.",
    timeline: [
      { date: "Siglos XVII–XIX", label: "Cavas y comercio", text: "La ladera bajo la plaza concentra almacenes, bodegas, tabernas y pequeños oficios." },
      { date: "1964", label: "Mesón del Champiñón", text: "Abre el establecimiento que convirtió una antigua cava en una parada castiza del centro." },
      { date: "Hoy", label: "Cierre del circuito", text: "Una tapa breve devuelve el paseo a la escala cotidiana, a pocos minutos del coche." }
    ],
    details: [{ kind: "context", label: "Cómo cerrar la historia", title: "La ciudad también se cuenta en una barra", text: "Reserva 20–30 minutos para una cerveza y los champiñones. Es un cierre deliberadamente pequeño después de palacios, plazas y avenidas.", extra: "Si conduces después, elige cerveza 0,0 o deja que conduzca otra persona." }]
  },
  3: {
    subtitle: "Acto I · del mercado de abastos al mercado de experiencias",
    description: "Al salir de la cava, el relato salta al Madrid del siglo XX. El Mercado de San Miguel nació en 1916 como mercado de abastos, cuando la ciudad necesitaba estructuras higiénicas y resistentes para vender alimentos en pleno centro. El hierro y el cristal hablan de esa modernización. Desde 2009 funciona como mercado gastronómico: el mismo impulso de abastecer a la ciudad, convertido en una experiencia para visitantes.",
    curiosity: "Es uno de los pocos mercados de hierro de Madrid que conserva su estructura original. Su segunda vida no borra la primera: fíjate en la retícula, pensada para ordenar puestos, mercancías y circulación.",
    timeline: [
      { date: "1916", label: "Mercado de abastos", text: "Se inaugura la estructura metálica de Alfonso Dubé y Díez para el comercio cotidiano del barrio." },
      { date: "2009", label: "Mercado gastronómico", text: "Reabre con puestos de producto y cocina preparada, anticipando el nuevo centro turístico." }
    ],
    details: [{ kind: "look", label: "Comer con contexto", title: "Primero recorre, después elige", text: "Mira cómo el edificio sigue siendo una máquina de circulación: entradas, pasillos, puestos y encuentros. Después comparte bacalao, croquetas, atún, ibéricos, quesos y un postre.", extra: "La comida es aquí una pausa narrativa: del abastecimiento de la capital a la gastronomía como ocio." }]
  },
  4: {
    subtitle: "Acto I · la villa medieval que aún gobierna",
    description: "Toma Conde de Miranda, la plaza del Conde de Barajas y la calle del Codo. En Plaza de la Villa aparece la escala de la Madrid medieval: antes de grandes avenidas y palacios, el gobierno se organizaba alrededor de una iglesia y unas pocas casas de linaje. La Casa y Torre de los Lujanes, la Casa de Cisneros y la antigua Casa de la Villa forman una pequeña lección de poder municipal.",
    curiosity: "La plaza se llamó de San Salvador por la iglesia donde se reunía el concejo. El nombre recuerda que Madrid fue primero una villa con gobierno propio, mucho antes de ser capital de una monarquía global.",
    timeline: [
      { date: "1202", label: "Fuero de Madrid", text: "La villa aparece ya como comunidad organizada con normas y obligaciones propias." },
      { date: "Siglos XV–XVI", label: "Casas de linaje", text: "Los Lujanes y Cisneros levantan torres y palacios junto al centro municipal." },
      { date: "Siglo XVII", label: "Casa de la Villa", text: "El ayuntamiento se instala en un edificio representativo de la nueva capital de los Austrias." }
    ],
    details: [{ kind: "look", label: "Fíjate en esto", title: "La curva de la calle del Codo", text: "La estrechez y la curva conservan la escala anterior a la capital. No es un decorado: es la huella del trazado que la corte transformó sin borrar por completo.", extra: "Al salir hacia Calle Mayor, busca los restos de Santa María, otra capa del Madrid anterior a la catedral." }]
  },
  5: {
    subtitle: "Acto II · una capital busca su catedral",
    description: "Sigue por Calle Mayor hasta la Almudena. Madrid fue capital desde 1561, pero tardó siglos en tener una catedral propia: esa demora explica la mezcla de estilos y la larga construcción del templo. La primera piedra se colocó en 1883 y la consagración llegó en 1993. Desde la cornisa, la iglesia, el Palacio Real y el Campo del Moro forman una imagen precisa de la alianza entre ciudad, monarquía y religión.",
    curiosity: "La fachada que mira al Palacio adopta una composición neoclásica para dialogar con el conjunto real; la cripta y la cabecera conservan un lenguaje neogótico más cercano al proyecto original.",
    timeline: [
      { date: "1883", label: "Primera piedra", text: "Comienza el proyecto de una catedral para la capital, junto al solar del antiguo alcázar." },
      { date: "1885", label: "Diócesis de Madrid", text: "Madrid se convierte en diócesis independiente, reforzando la necesidad de una sede catedralicia." },
      { date: "1993", label: "Consagración", text: "Juan Pablo II consagra la catedral después de un siglo de proyectos y pausas." }
    ],
    details: [{ kind: "look", label: "Lee el paisaje", title: "La capital desde su cornisa", text: "Mira al oeste: el Palacio Real ocupa el lugar del poder y la Casa de Campo abre la ciudad hacia el paisaje. La Almudena es el contrapunto religioso de esa composición.", extra: "Aquí basta con rodear el exterior; la visita interior es otra decisión de tiempo." }]
  },
  6: {
    subtitle: "Acto II · del alcázar medieval al palacio borbónico",
    description: "Cruza la Plaza de la Armería. Bajo el palacio actual estuvo el alcázar medieval y, después, la residencia de los Austrias. Un incendio destruyó el edificio en la Nochebuena de 1734; Felipe V decidió levantar una nueva imagen de la monarquía, más monumental y resistente al fuego. Juan Bautista Sacchetti continuó el proyecto de Filippo Juvarra y el palacio quedó terminado en 1755, ya bajo Fernando VI.",
    curiosity: "El nuevo palacio se construyó casi por completo en piedra y ladrillo, sin madera estructural, como respuesta directa al incendio del antiguo alcázar. Carlos III lo convirtió en residencia estable de la corte.",
    timeline: [
      { date: "Siglos IX–XVII", label: "Alcázar y corte", text: "La fortaleza islámica y el alcázar de los Austrias hacen del promontorio el centro del poder madrileño." },
      { date: "1734", label: "Incendio del Alcázar", text: "El fuego destruye la residencia de los Austrias durante la Nochebuena." },
      { date: "1738–1755", label: "Palacio nuevo", text: "Los Borbones levantan el edificio actual como declaración de continuidad y renovación." }
    ],
    details: [{ kind: "look", label: "Fíjate en esto", title: "La fachada como mensaje", text: "Desde la Puerta del Príncipe, observa la escala y la regularidad del conjunto. Ya no es una fortaleza: es una máquina ceremonial para hacer visible la monarquía.", extra: "La Galería de las Colecciones Reales puede ampliar este capítulo, pero añade una visita interior completa." }]
  },
  7: {
    subtitle: "Acto II · la monarquía convierte la ciudad en escenario",
    description: "Sal del Palacio hacia Oriente y el Teatro Real. Esta plaza no es medieval: nació de una operación urbana que quiso abrir un gran espacio representativo frente a la residencia real. Fernando VII impulsó su ordenación en 1817; el Teatro Real comenzó a construirse en 1818 y abrió en 1850. Las esculturas de reyes, pensadas para coronar el palacio, terminaron repartidas por Madrid.",
    curiosity: "La Plaza de Oriente resume una transformación decisiva: la ciudad deja de crecer solo alrededor de calles y parroquias y empieza a organizarse mediante ejes, perspectivas y espacios ceremoniales.",
    timeline: [
      { date: "1817", label: "Nueva plaza real", text: "Fernando VII ordena transformar el entorno del Palacio en un espacio monumental y ajardinado." },
      { date: "1818–1850", label: "Teatro Real", text: "Se construye y abre el gran teatro de la corte frente al Palacio Real." }
    ],
    details: [{ kind: "look", label: "Fíjate en esto", title: "De la corte al paseo", text: "Rodea el Teatro Real y sigue por Ópera hacia Bailén. El eje cambia de escala: del escenario de la monarquía a la salida abierta hacia Debod.", extra: "La dirección importa: avanzas hacia el oeste ahora y regresarás por Gran Vía y Sol, sin deshacer el camino." }]
  },
  11: {
    subtitle: "Acto II · Madrid entra en la historia global",
    description: "El Templo de Debod introduce una ciudad distinta: la capital que participa en una operación internacional de salvamento patrimonial. En los años sesenta, la presa de Asuán amenazó monumentos de Nubia. España colaboró en la campaña de la UNESCO y en 1964 pidió que Debod fuera donado al país. Egipto lo entregó en 1968; no fue una compra en subasta, sino una donación diplomática entre los países que más contribuyeron al rescate.",
    curiosity: "Egipto repartió varios templos entre países colaboradores —entre ellos Estados Unidos, Italia, Países Bajos y España—. Debod fue desmontado, trasladado y reconstruido piedra a piedra en Madrid entre 1970 y 1972.",
    timeline: [
      { date: "Siglo II a. C.", label: "Nace Debod", text: "El rey Adijalamani levanta el núcleo del templo nubio dedicado a Amón e Isis." },
      { date: "1960–1968", label: "Salvamento de Nubia", text: "La campaña internacional de la UNESCO protege monumentos amenazados por la presa de Asuán." },
      { date: "1972", label: "Debod en Madrid", text: "El templo reconstruido se abre al público junto al Parque del Oeste." }
    ],
    details: [{ kind: "look", label: "Cómo leer esta parada", title: "Un monumento fuera de lugar, pero no sin historia", text: "No hace falta esperar al atardecer. Mira el templo como testimonio de cooperación internacional, de ingeniería y de la nueva vocación cultural de Madrid.", extra: "Cruza hacia Plaza de España y continúa al este por Gran Vía: el regreso cuenta ahora la historia de la ciudad moderna." }]
  },
  10: {
    subtitle: "Acto III · la ciudad se abre a la modernidad",
    description: "Desde Plaza de España entra en Gran Vía y camina hacia el este. La avenida fue una operación de cirugía urbana: desde 1910 abrió un eje ancho entre calles estrechas, desplazó vecinos y negocios y creó una nueva fachada para la capital. El Edificio España, la Torre de Madrid, los cines y los teatros muestran cómo Madrid aprendió a vender espectáculo, consumo y velocidad.",
    curiosity: "La Gran Vía no se construyó de una vez: sus tramos se abrieron por fases y cambiaron de nombre varias veces. La ciudad moderna es, también, una obra inacabada.",
    timeline: [
      { date: "1910", label: "Primera piedra", text: "Alfonso XIII inicia la apertura del gran eje que atraviesa el centro histórico." },
      { date: "1929–1930", label: "Callao y rascacielos", text: "Los nuevos tramos consolidan una avenida de cines, hoteles, oficinas y grandes almacenes." },
      { date: "Hoy", label: "Eje peatonal y cultural", text: "La avenida sigue funcionando como escaparate de la transformación urbana de Madrid." }
    ],
    details: [{ kind: "look", label: "Mira hacia arriba", title: "La ciudad como fachada", text: "Camina hacia Callao y compara las escalas: palacios comerciales, marquesinas, torres y anuncios. Cada edificio cuenta una versión distinta de la modernidad.", extra: "En Callao harás una pausa panorámica antes de bajar por Preciados hacia Sol." }]
  },
  9: {
    subtitle: "Acto III · cine, consumo y la ciudad espectáculo",
    description: "Callao concentra el Madrid de masas. El edificio Capitol, terminado en 1933, fue concebido como cine, hotel y oficinas; su neón convirtió la esquina en una imagen reconocible de la ciudad. Sube a la Gourmet Experience de El Corte Inglés: la terraza ofrece una lectura en altura de Gran Vía, una avenida nacida para el tráfico y convertida después en escenario de consumo, ocio y turismo.",
    curiosity: "El Capitol combina una planta triangular, una torre escalonada y una gran pantalla curva: arquitectura, publicidad y cine se funden en un solo objeto urbano.",
    timeline: [
      { date: "1933", label: "Edificio Capitol", text: "Abre el complejo de cine, hotel y oficinas que fija la imagen moderna de Callao." },
      { date: "Siglo XX", label: "Madrid de los cines", text: "Callao se convierte en uno de los grandes escaparates de ocio y publicidad de la capital." },
      { date: "Hoy", label: "La ciudad en altura", text: "La terraza permite leer en una sola mirada el eje de Gran Vía y sus distintas épocas." }
    ],
    details: [{ kind: "look", label: "Pausa con perspectiva", title: "Una terraza para entender la avenida", text: "Desde la planta 9, alinea el Capitol, los teatros y el Edificio España. No es solo una vista: es la secuencia histórica de la Gran Vía.", extra: "Toma café, postre o una copa; la comida principal ya quedó atrás en San Miguel. El acceso y los horarios pueden variar." }]
  },
  8: {
    subtitle: "Acto III · la plaza donde Madrid se hace política",
    description: "Baja por Preciados hasta Sol, el gran nudo del centro. La plaza nació junto a una puerta de la cerca medieval, pero su forma actual pertenece a la ciudad borbónica y liberal: la Casa de Correos se levantó entre 1760 y 1768, y la plaza fue escenario de la revuelta del 2 de mayo de 1808, manifestaciones, celebraciones y protestas. Aquí la historia deja de ser palacio y se vuelve multitud.",
    curiosity: "El Kilómetro Cero marca el origen convencional de las carreteras radiales; la placa está frente a la Casa de Correos, hoy sede de la Comunidad de Madrid. El metro llegó en 1919.",
    timeline: [
      { date: "1760–1768", label: "Casa de Correos", text: "El edificio de la plaza se convierte en una pieza clave de la administración borbónica." },
      { date: "1808", label: "2 de mayo", text: "Sol y sus alrededores participan en la insurrección madrileña contra la ocupación napoleónica." },
      { date: "1919", label: "Primer metro", text: "La primera línea conecta Sol con Cuatro Caminos y transforma la movilidad del centro." }
    ],
    details: [{ kind: "context", label: "Ritmo del cierre", title: "La plaza de la multitud", text: "Haz una vuelta breve por el perímetro: Correos, Kilómetro Cero, el Oso y el Madroño, Carlos III y el cartel de Tío Pepe.", extra: "Después sigue por Calle Mayor. Son unos 10–12 minutos hasta el Champiñón y pocos minutos más hasta el parking." }]
  }
};
Object.entries(HISTORICAL_COPY).forEach(([id, copy]) => Object.assign(STOPS.find((stop) => stop.id === Number(id)), copy));

const KEYS = { visited: "madrid-centro-tour:visited-stops", provider: "madrid-centro-tour:map-provider", optional: "madrid-centro-tour:include-gallery" };
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const state = { visited: read(KEYS.visited, []), provider: read(KEYS.provider, "ask"), optional: read(KEYS.optional, false), active: 0 };
const $ = (selector, root = document) => root.querySelector(selector);
function mainStops() { const stops = ROUTE_ORDER.map((id) => STOPS.find((stop) => stop.id === id)).filter(Boolean); if (state.optional) { const palaceIndex = stops.findIndex((stop) => stop.id === 6); stops.splice(palaceIndex + 1, 0, GALLERY); } return stops; }
function renumberStops() { document.querySelectorAll("[data-stop-id]").forEach((article, index) => { const number = String(index + 1).padStart(2, "0"); const numberElement = $(".stop__number", article); const tagElement = $(".stop__tag", article); if (numberElement) numberElement.textContent = number; if (tagElement && !article.classList.contains("stop--optional")) tagElement.textContent = `Parada ${number}`; }); }

function googlePlace(stop) { return `https://www.google.com/maps/search/?api=1&query=${stop.coordinates.lat},${stop.coordinates.lng}`; }
function googleDirections(from, to) { const origin = from ? `&origin=${from.coordinates.lat},${from.coordinates.lng}` : ""; return `https://www.google.com/maps/dir/?api=1${origin}&destination=${to.coordinates.lat},${to.coordinates.lng}&travelmode=walking`; }
function osmandPoint(stop) { return `https://osmand.net/map/?pin=${stop.coordinates.lat},${stop.coordinates.lng}#18/${stop.coordinates.lat}/${stop.coordinates.lng}`; }
function osmandNavigate(to) { return `https://osmand.net/map/navigate/?finish=${to.coordinates.lat},${to.coordinates.lng}&type=osmand&profile=pedestrian`; }
function mapUrl(action, stop, next) { if (state.provider === "osmand") return action === "place" ? osmandPoint(stop) : osmandNavigate(next || stop); return action === "place" ? googlePlace(stop) : googleDirections(null, next || stop); }
function imageFigure(stop) { const image = IMAGE_URLS[stop.id] || stop.image; if (!image) return `<div class="stop__image stop__image--fallback" data-mark="${String(stop.id).padStart(2, "0")}" aria-hidden="true"></div>`; const credit = stop.imageCredit ? ` · Foto: <a href="${stop.imageCredit.url}" target="_blank" rel="noreferrer">${stop.imageCredit.author}</a>` : ""; return `<figure class="stop__image"><img src="${image}" alt="${stop.alt}" loading="lazy" width="${stop.imageWidth || 1600}" height="${stop.imageHeight || 1067}" data-parallax /><figcaption>${stop.name}${credit}</figcaption></figure>`; }
function stopTemplate(stop, index, visible) {
  const next = visible[index + 1]; const isVisited = state.visited.includes(stop.id); const last = !next;
  const timelineItems = stop.timeline || []; const timeline = timelineItems.length ? `<div class="stop__timeline"><span class="stop__timeline-label">Hitos en el tiempo</span>${timelineItems.map((item) => `<div><strong>${glossaryMarkup(item.date)}</strong><span><b>${glossaryMarkup(item.label)}</b>${glossaryMarkup(item.text)}</span></div>`).join("")}</div>` : "";
  const details = (stop.details || []).map((detail) => `<aside class="stop__detail stop__detail--${detail.kind}"><strong>${glossaryMarkup(detail.label)}</strong><h3>${glossaryMarkup(detail.title)}</h3><p>${glossaryMarkup(detail.text)}</p>${detail.extra ? `<p>${glossaryMarkup(detail.extra)}</p>` : ""}${detail.prompt ? `<p class="stop__detail-prompt">${glossaryMarkup(detail.prompt)}</p>` : ""}</aside>`).join("");
  const nextBlock = next ? `<div class="stop__next"><small>Siguiente · ${next.duration}</small><a href="#parada-${next.id}">${next.name} <span aria-hidden="true">↘</span></a></div>` : `<div class="stop__next"><small>Fin del circuito</small><span>Volver al parking de Plaza Mayor</span></div>`;
  const navigateLabel = last ? "Volver al parking" : "Caminar a la siguiente";
  return `<article class="stop${stop.optional ? " stop--optional" : ""}${isVisited ? " is-visited" : ""}" id="parada-${stop.id}" data-stop-id="${stop.id}"><div class="stop__grid"><div class="stop__copy"><p class="stop__number" aria-hidden="true">${String(stop.id).padStart(2, "0")}</p><p class="stop__tag">${stop.optional ? "Parada opcional" : `Parada ${String(stop.id).padStart(2, "0")}`}</p><h2>${glossaryMarkup(stop.name)}</h2><p class="stop__subtitle">${glossaryMarkup(stop.subtitle)}</p><p class="stop__description">${glossaryMarkup(stop.description)}</p>${timeline}${details}<div class="stop__meta"><span>◷ ${stop.duration}</span><span>◌ ${stop.price}</span></div><aside class="stop__curiosity"><strong>Dato curioso</strong><p>${glossaryMarkup(stop.curiosity)}</p></aside><div class="stop__actions"><button class="button button--accent" type="button" data-navigate="${stop.id}">${navigateLabel} <span aria-hidden="true">↗</span></button><button class="button button--outline" type="button" data-place="${stop.id}">Ver este lugar</button><button class="button button--outline" type="button" data-copy="${stop.id}">Copiar coordenadas</button><button class="visit-toggle" type="button" data-visit="${stop.id}" aria-pressed="${isVisited}"><span class="visit-toggle__box" aria-hidden="true"></span>${isVisited ? "Visitada" : "Marcar como visitada"}</button></div><div class="stop__sources"><a class="source-link" href="${stop.source}" target="_blank" rel="noreferrer">Información oficial ↗</a>${stop.sourceExtra ? `<a class="source-link" href="${stop.sourceExtra}" target="_blank" rel="noreferrer">${stop.sourceExtraLabel || "Referencia adicional"} ↗</a>` : ""}</div>${nextBlock}</div><div class="stop__media">${imageFigure(stop)}</div></div></article>`;
}
function render() { const visible = mainStops(); $("[data-stops]").innerHTML = visible.map((stop, index) => stopTemplate(stop, index, visible)).join(""); renumberStops(); $("[data-progress]").textContent = `${visible.filter((stop) => state.visited.includes(stop.id)).length} / ${visible.length}`; $("[data-optional-toggle]").textContent = state.optional ? "Quitar Galería opcional" : "Añadir Galería de las Colecciones Reales"; bindStopEvents(); observeStops(); updateParallax(); }
function openProviderDialog(action, stopId) { const dialog = $("[data-map-dialog]"); dialog.dataset.action = action; dialog.dataset.stopId = stopId; if (typeof dialog.showModal === "function") dialog.showModal(); else dialog.setAttribute("open", ""); }
function launchMap(action, stopId) { const visible = mainStops(); const stop = visible.find((item) => item.id === Number(stopId)); if (!stop) return; const index = visible.indexOf(stop); const next = visible[index + 1]; if (action === "return") { const parking = STOPS[0]; if (state.provider === "ask") return openProviderDialog("return", parking.id); window.location.href = mapUrl("navigate", stop, parking); return; } if (action === "navigate" && !next) { if (state.provider === "ask") return openProviderDialog("return", stop.id); window.location.href = mapUrl("navigate", stop, STOPS[0]); return; } if (state.provider === "ask") return openProviderDialog(action, stop.id); window.location.href = mapUrl(action, stop, next); }
function bindStopEvents() { document.querySelectorAll("[data-visit]").forEach((button) => button.addEventListener("click", () => { const id = Number(button.dataset.visit); const at = state.visited.indexOf(id); if (at < 0) state.visited.push(id); else state.visited.splice(at, 1); write(KEYS.visited, state.visited); render(); document.getElementById(`parada-${id}`)?.scrollIntoView({ behavior: "smooth", block: "start" }); })); document.querySelectorAll("[data-place], [data-navigate]").forEach((button) => button.addEventListener("click", () => launchMap(button.dataset.place ? "place" : "navigate", button.dataset.place || button.dataset.navigate))); document.querySelectorAll("[data-copy]").forEach((button) => button.addEventListener("click", async () => { const stop = mainStops().find((item) => item.id === Number(button.dataset.copy)); if (!stop) return; const coordinates = `${stop.coordinates.lat}, ${stop.coordinates.lng}`; try { await navigator.clipboard.writeText(coordinates); } catch { window.prompt("Copia estas coordenadas", coordinates); } const original = button.textContent; button.textContent = "Coordenadas copiadas"; window.setTimeout(() => { button.textContent = original; }, 1800); })); }
function observeStops() { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (!entry.isIntersecting) return; state.active = Number(entry.target.dataset.stopId); const stop = mainStops().find((item) => item.id === state.active); $("[data-current-label]").textContent = stop?.shortName || "Ruta"; }), { rootMargin: "-35% 0px -55%", threshold: 0 }); document.querySelectorAll("[data-stop-id]").forEach((section) => observer.observe(section)); }
let parallaxFrame; function updateParallax() { parallaxFrame = undefined; if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; document.querySelectorAll("[data-parallax]").forEach((image) => { const box = image.closest(".stop__media").getBoundingClientRect(); const distance = (box.top + box.height / 2 - window.innerHeight / 2) / window.innerHeight; image.style.setProperty("--parallax", `${Math.max(-5, Math.min(5, distance * -3))}%`); }); }
window.addEventListener("scroll", () => { if (!parallaxFrame) parallaxFrame = requestAnimationFrame(updateParallax); }, { passive: true });
document.querySelector("[data-settings]").addEventListener("click", () => openProviderDialog("settings", 0));
document.querySelector("[data-optional-toggle]").addEventListener("click", () => { state.optional = !state.optional; write(KEYS.optional, state.optional); render(); });
document.querySelectorAll("[data-provider]").forEach((button) => button.addEventListener("click", () => { const dialog = $("[data-map-dialog]"); if (button.dataset.provider === "copy") { dialog.close(); return; } state.provider = button.dataset.provider; write(KEYS.provider, state.provider); const action = dialog.dataset.action; const stopId = dialog.dataset.stopId; dialog.close(); if (["place", "navigate", "return"].includes(action)) launchMap(action, stopId); }));
let lastGlossaryTrigger; function openGlossary(key, trigger) { const entry = GLOSSARY.find((item) => item.key === key); const dialog = $("[data-glossary-dialog]"); if (!entry) return; lastGlossaryTrigger = trigger; $("[data-glossary-title]", dialog).textContent = entry.title; $("[data-glossary-definition]", dialog).textContent = entry.definition; if (typeof dialog.showModal === "function") dialog.showModal(); else dialog.setAttribute("open", ""); }
document.addEventListener("click", (event) => { const trigger = event.target instanceof Element ? event.target.closest("[data-glossary]") : null; if (trigger) openGlossary(trigger.dataset.glossary, trigger); });
const glossaryDialog = $("[data-glossary-dialog]"); glossaryDialog.addEventListener("click", (event) => { if (event.target === event.currentTarget) event.currentTarget.close(); }); glossaryDialog.addEventListener("close", () => { lastGlossaryTrigger?.focus(); lastGlossaryTrigger = undefined; });
$("[data-download-gpx]").addEventListener("click", () => { const waypoints = mainStops().map((stop) => `  <wpt lat="${stop.coordinates.lat}" lon="${stop.coordinates.lng}"><name>${stop.id}. ${stop.name}</name><desc>${stop.subtitle}</desc></wpt>`).join("\n"); const gpx = `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Madrid centro paseo a pie" xmlns="http://www.topografix.com/GPX/1/1">\n${waypoints}\n</gpx>`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([gpx], { type: "application/gpx+xml" })); link.download = state.optional ? "madrid-centro-ruta-ampliada.gpx" : "madrid-centro-ruta.gpx"; link.click(); URL.revokeObjectURL(link.href); });
$("[data-map-dialog]").addEventListener("click", (event) => { if (event.target === event.currentTarget) event.currentTarget.close(); });
const topbar = $("[data-topbar]"); window.addEventListener("scroll", () => topbar.classList.toggle("is-scrolled", window.scrollY > 20), { passive: true });
render(); if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("sw.js"));
